version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}          # Database name
      POSTGRES_USER: ${POSTGRES_USER}      # Database user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Database user password
    ports:
      - "6024:5432"                        # Exposing port for accessing the DB
    networks:
      - app-network

  app:
    build:
      context: .
    image: chainlit-bdrag
    container_name: chainlit-bdrag-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}          
      POSTGRES_USER: ${POSTGRES_USER}      
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge